version: 2
ethernets:
  enp1s0:
    dhcp4: false
    addresses:
      - BRIDGE_VM_IP/24
    routes:
      - to: default
        via: BRIDGE_HOST_IP
    nameservers:
      addresses:
        - BRIDGE_HOST_IP
